### PR TITLE
Changes for compatibility of nginx proxy with Shiny 1.3

### PR DESCRIPTION
**Pull request by andresrcs**
Further explanation can be found here:
https://community.rstudio.com/t/having-problems-with-shiny-v1-3-0-and-nginx/28180/2

### CODE REVIEW

**Comment by daattali** [comment]
That seems like quite a bit of changes to the configuration - have you tested that these exact instructions work? And that the issue with trailing slashes (`example.com/shiny/app` and `example.com/shiny/app/`) still works with this config?

I'm a bit worried to make so many changes without testing it - do you think simply instructing people to `remotes::install_github("rstudio/httpuv")` for the next couple weeks will be enough?

**Comment by andresrcs** [comment]
Yes, I have this changes deployed on two (Ubuntu and Debian) servers and both kind of urls work as well. Also, this is the official recommended configuration by RStudio for nginx and RStudio products.

I think that redirecting people to the development version of httpuv would work but the configuration would still be suboptimal.

**Comment by daattali** [comment]
I really appreciate you bringing this issue to my attention, and especially the fact that you took the time to do this PR when I asked for it. Thank you for your time.

I'm a bit hesitant to make such drastic changes to the config because this configuration setting has been proved to work across many versions of packages, nginx, ubuntus, shiny servers... There actually is a problem with RStudio's recommended config settings (I have an open issue about it: https://github.com/rstudio/shiny-server/issues/387) and my config settings avoid that issue. So I would much rather stick to the one that I know works.

It looks like simply updating httpuv to the latest version is a valid solution as well, and is much simpler, so I would rather go with that.

**Comment by andresrcs** [comment]
That sounds reasonable but what about just  changing the conflictive part and letting the trailing slash issue as it is, like in your example? 
```
map $http_upgrade $connection_upgrade {
        default upgrade;
        ''      close;
}

server {
        listen 80 default_server;
        listen [::]:80 default_server;

        root /var/www/html;

        index index.html index.htm index.nginx-debian.html;

        server_name _;

        location / {
                try_files $uri $uri/ =404;
        }

        location /shiny/ {
                rewrite ^(/shiny/[^/]+)$ $1/ permanent;
                proxy_pass http://127.0.0.1:3838/;
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection $connection_upgrade;
        }
}
```

**Comment by daattali** [comment]
What specifically is the difference in this one?

---
Dean Attali
President & CEO
AttaliTech Ltd
http://AttaliTech.com <http://attalitech.com>

**Comment by andresrcs** [comment]
Sorry, I'm not getting your question, i'm not a native English speaker, what the difference is related to what? I'm talking about changing the config that currently is your article by the config that you posted on this github issue rstudio/shiny-server#387

The difference would be using 

```
map $http_upgrade $connection_upgrade {
        default upgrade;
        ''      close;
}
...... 
.... 
... 
proxy_set_header Connection $connection_upgrade;
```
instead of

```
proxy_set_header Connection "upgrade";
```

**Comment by daattali** [comment]
Oh, yes, that's small enough and safe looking change that I would be comfortable with instead of the httpuv solution!

**Pull request closed without merging**
